version: "3.9"

services:
  origin:
    image: cdn-origin:latest
    ports:
      - "8080:80"
    networks:
      - cdn-net

  edge:
    image: cdn-edge1:latest   # образ тот же, что и для edge1
    deploy:
      replicas: 2             # вместо edge1 и edge2 — один сервис с двумя репликами
    networks:
      - cdn-net

  load-balancer:
    image: cdn-load-balancer:latest
    ports:
      - "8082:80"
    networks:
      - cdn-net

  monitoring:
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - "8083:8080"
    networks:
      - cdn-net
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  cdn-net:
    driver: overlay